### ISSUE TITLE
SIO_LOOPBACK_FAST_PATH unsupported by Windows 7

### ISSUE THREAD

**Issue by milanmilas** [fedjabosnic/hotfix#51]
Exception running on windows 7:
The attempted operation is not supported for the type of object referenced

   at System.Net.Sockets.Socket.IOControl(Int32 ioControlCode, Byte[] optionInValue, Byte[] optionOutValue)
   at HotFix.Transport.TcpTransport.Accept(String address, Int32 port) in C:\GitHub\hotfix\HotFix\Transport\TcpTransport.cs:line 34
   at HotFix.Transport.TcpTransport.Create(Boolean server, String address, Int32 port) in C:\GitHub\hotfix\HotFix\Transport\TcpTransport.cs:line 15
   at HotFix.Core.Engine.<>c.<.ctor>b__24_2(IConfiguration c) in C:\GitHub\hotfix\HotFix\Core\Engine.cs:line 29
   at HotFix.Core.Engine.Open(IConfiguration configuration) in C:\GitHub\hotfix\HotFix\Core\Engine.cs:line 48
   at HotFix.Program.<>c__DisplayClass5_0.<Main>b__0() in C:\GitHub\hotfix\HotFix\Program.cs:line 75

SIO_LOOPBACK_FAST_PATH control code
https://msdn.microsoft.com/en-us/library/windows/desktop/jj841212(v=vs.85).aspx

The attempted operation is not supported for the type of object referenced. This error is returned if the specified IOCTL command is not supported. This error is returned if the SIO_LOOPBACK_FAST_PATH IOCTL is used on Windows 7, Windows Server 2008 R2, and earlier versions.
This error is also returned if the SIO_LOOPBACK_FAST_PATH IOCTL is not supported by the transport provider.

https://blogs.technet.microsoft.com/wincat/2012/12/05/fast-tcp-loopback-performance-and-low-latency-with-windows-server-2012-tcp-loopback-fast-path/

**Comment by fedjabosnic** [comment]
@milanmilas Best we can do is ignore the error and accept the worse performance on platforms older than Windows 8 or Server 2012, see linked pull request #52

**Comment by fedjabosnic** [comment]
Resolved with #52
